name: Delete Artifacts by Date and Repo

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'The repository (owner/repo) whose artifacts you want to delete'
        required: true
        type: string
      target_date:
        description: 'Delete artifacts created on this date (YYYY-MM-DD)'
        required: true
        type: string

permissions:
  contents: write

env:
  # Must be a PAT (or token) that has repo:actions permission on the target repository
  TARGET_REPO_PAT: ${{ secrets.PAT_TOKEN }}

jobs:
  delete_artifacts:
    name: Delete Artifacts on ${{ github.event.inputs.target_date }} from ${{ github.event.inputs.target_repo }}
    runs-on: ubuntu-latest
    steps:
      - name: Install jq if missing
        shell: bash
        run: |
          if ! command -v jq &> /dev/null; then
            echo "Installing jq…"
            apt-get update -qy
            apt-get install -qy jq
          fi

      - name: Validate inputs
        shell: bash
        run: |
          REPO="${{ github.event.inputs.target_repo }}"
          DATE="${{ github.event.inputs.target_date }}"
          if [[ -z "$REPO" ]]; then
            echo "Error: target_repo is required."
            exit 1
          fi
          if [[ ! "$REPO" =~ ^[^/]+/[^/]+$ ]]; then
            echo "Error: target_repo must be in 'owner/repo' format."
            exit 1
          fi
          if [[ -z "$DATE" ]]; then
            echo "Error: target_date is required."
            exit 1
          fi
          if [[ ! "$DATE" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            echo "Error: target_date must be YYYY-MM-DD."
            exit 1
          fi
          echo "Inputs validated: REPO=$REPO, DATE=$DATE"

      - name: List & Delete artifacts for the given date
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          TARGET_REPO: ${{ github.event.inputs.target_repo }}
          TARGET_DATE: ${{ github.event.inputs.target_date }}
        run: |
          echo "Fetching artifacts from $TARGET_REPO created on $TARGET_DATE …"

          # 1) Call the API to fetch all artifacts
          RESPONSE=$(curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$TARGET_REPO/actions/artifacts")

          # 2) Check for API-level errors (e.g. 404 = repo not found or insufficient permissions)
          MESSAGE=$(echo "$RESPONSE" | jq -r '.message // empty')
          if [[ "$MESSAGE" == "Not Found" ]]; then
            echo "Error: Repository '$TARGET_REPO' not found or insufficient permissions."
            echo "Make sure TARGET_REPO_PAT has access to list artifacts on $TARGET_REPO."
            exit 1
          fi
          if [[ -n "$MESSAGE" && "$MESSAGE" != "null" ]]; then
            echo "Error: Unexpected API message: $MESSAGE"
            exit 1
          fi

          # 3) If .artifacts is null/empty, inform the user
          EXISTS=$(echo "$RESPONSE" | jq '.artifacts // empty')
          if [[ -z "$EXISTS" ]]; then
            echo "→ No artifacts key in response. Either there truly are no artifacts, or the PAT lacks permission."
            echo "→ Raw response snippet: ${RESPONSE:0:200}"
            exit 0
          fi

          # 4) Extract IDs for artifacts whose created_at starts with TARGET_DATE
          ARTIFACT_IDS=$(echo "$RESPONSE" | jq -r --arg TD "$TARGET_DATE" '
            .artifacts[]
            | select(.created_at | startswith($TD))
            | .id
          ')

          if [ -z "$ARTIFACT_IDS" ]; then
            echo "No artifacts found in $TARGET_REPO with created_at = $TARGET_DATE"
            exit 0
          fi

          echo "Found artifact IDs to delete:"
          echo "$ARTIFACT_IDS"

          # 5) Delete each artifact by ID
          echo "$ARTIFACT_IDS" | while read -r ID; do
            echo "→ Deleting artifact ID $ID"
            curl -s -X DELETE \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$TARGET_REPO/actions/artifacts/$ID"
          done

          echo "Completed deletion of artifacts created on $TARGET_DATE from $TARGET_REPO."
